# Generated by Django 4.1 on 2022-09-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
