# Generated by Django 4.1 on 2022-09-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_category_blog_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categories',
            new_name='category',
        ),
    ]
