# Generated by Django 4.1 on 2022-09-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_user_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_home',
        ),
    ]
