# Generated by Django 4.1 on 2022-09-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_user_is_active_alter_user_is_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
