# Generated by Django 4.1 on 2022-09-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_rename_username_user_surename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surename',
            new_name='surname',
        ),
    ]
