# Generated by Django 4.1 on 2022-09-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_user_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categorys',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
